require('dotenv').config();
const pool = require('../db');

const tourData = [
  { city: "Baltimore", state: "Maryland", description: "Discover a harbor city bursting with creativity, culture, and waterfront energy — from the iconic Inner Harbor, vibrant Fells Point and Federal Hill neighborhoods, and rich maritime history, to local art at the Baltimore Museum of Art and flavors of Maryland blue crab.", highlights: ["Explore the historic Inner Harbor", "Visit Fells Point neighborhood", "Tour Baltimore Museum of Art", "Experience Federal Hill views", "Taste Maryland blue crab", "Discover maritime history"], startDate: "April 27, 2026", endDate: "May 3, 2026", maxParticipants: 36, imageUrl: "/api/images/baltimore.png" },
  { city: "Wilmington & Rehoboth Beach", state: "Delaware", description: "Experience Delaware's perfect blend of historic charm and coastal beauty. From Wilmington's vibrant downtown and DuPont heritage sites to the pristine beaches and boardwalk of Rehoboth Beach, discover the First State's diverse treasures.", highlights: ["Tour DuPont mansions and gardens", "Explore Wilmington Riverfront", "Relax on Rehoboth Beach boardwalk", "Visit Delaware Art Museum", "Enjoy fresh seafood dining", "Discover tax-free shopping"], startDate: "May 4, 2026", endDate: "May 10, 2026", maxParticipants: 36, imageUrl: "/api/images/delaware.png" },
  { city: "Philadelphia & Pittsburgh", state: "Pennsylvania", description: "Journey through Pennsylvania's iconic cities - from Philadelphia's birthplace of American democracy and vibrant arts scene to Pittsburgh's transformed waterfront and innovative spirit. Experience the Keystone State's rich history and modern energy.", highlights: ["See the Liberty Bell and Independence Hall", "Explore Philadelphia Museum of Art", "Visit Pittsburgh's Strip District", "Tour Andy Warhol Museum", "Experience cheesesteak culture", "Discover Steel City transformation"], startDate: "May 11, 2026", endDate: "May 17, 2026", maxParticipants: 36, imageUrl: "/api/images/pennsylvania.png" },
  { city: "West Orange & Camden", state: "New Jersey", description: "Uncover New Jersey's innovation heritage and waterfront renaissance. From Thomas Edison's laboratory in West Orange to Camden's revitalized waterfront with spectacular Philadelphia skyline views, experience the Garden State's hidden gems.", highlights: ["Tour Edison National Historic Site", "Visit Adventure Aquarium in Camden", "Explore Battleship New Jersey", "Discover South Mountain Reservation", "Experience waterfront entertainment", "Enjoy diverse culinary scene"], startDate: "May 18, 2026", endDate: "May 24, 2026", maxParticipants: 36, imageUrl: "/api/images/newjersey.png" },
  { city: "Bronx & Brooklyn", state: "New York", description: "Immerse yourself in New York City's diverse boroughs. From the Bronx Zoo and Yankee Stadium to Brooklyn's vibrant neighborhoods, world-class museums, and iconic Brooklyn Bridge, discover the authentic heart of the Big Apple.", highlights: ["Visit Bronx Zoo and Botanical Garden", "Tour Yankee Stadium", "Walk Brooklyn Bridge", "Explore DUMBO and Williamsburg", "Experience Brooklyn Museum", "Enjoy diverse food scenes"], startDate: "May 25, 2026", endDate: "May 31, 2026", maxParticipants: 36, imageUrl: "/api/images/newyork.png" },
  { city: "Bridgeport & Mystic", state: "Connecticut", description: "Explore Connecticut's coastal treasures from Bridgeport's Barnum legacy and Sound views to Mystic's maritime heritage and charming seaport. Experience New England coastal culture at its finest.", highlights: ["Visit Mystic Seaport Museum", "Explore Beardsley Zoo", "Tour historic whaling village", "Experience maritime heritage", "Enjoy coastal seafood", "Discover local art galleries"], startDate: "June 1, 2026", endDate: "June 7, 2026", maxParticipants: 36, imageUrl: "/api/images/connecticut.png" },
  { city: "Providence & North Kingstown", state: "Rhode Island", description: "Discover Rhode Island's creative spirit and coastal charm. From Providence's renaissance as a cultural hub with world-class design schools to North Kingstown's pristine beaches and historic villages, experience the Ocean State's unique character.", highlights: ["Tour RISD Museum", "Explore WaterFire Providence", "Visit historic Wickford Village", "Discover Benefit Street architecture", "Enjoy fresh seafood", "Experience coastal beaches"], startDate: "June 8, 2026", endDate: "June 14, 2026", maxParticipants: 36, imageUrl: "/api/images/rhodeisland.png" },
  { city: "Boston", state: "Massachusetts", description: "Walk through America's revolutionary history and modern innovation in Boston. From the Freedom Trail and Fenway Park to world-class museums and vibrant neighborhoods, experience the city where American independence was born.", highlights: ["Walk the Freedom Trail", "Visit Faneuil Hall Marketplace", "Tour Fenway Park", "Explore Museum of Fine Arts", "Experience North End Italian cuisine", "Discover Boston Harbor"], startDate: "June 15, 2026", endDate: "June 21, 2026", maxParticipants: 36, imageUrl: "/api/images/massachusetts.png" },
  { city: "Holderness & Hampton Beach", state: "New Hampshire", description: "Experience New Hampshire's natural beauty and coastal fun. From the pristine lakes and White Mountains near Holderness to the lively Hampton Beach boardwalk, discover the Granite State's outdoor paradise.", highlights: ["Explore Squam Lake", "Visit Hampton Beach boardwalk", "Discover White Mountains views", "Experience lakeside activities", "Enjoy fresh seafood", "Tour scenic drives"], startDate: "June 22, 2026", endDate: "June 28, 2026", maxParticipants: 36, imageUrl: "/api/images/newhampshire.png" },
  { city: "Burlington", state: "Vermont", description: "Discover Burlington's perfect blend of natural beauty and creative culture. Nestled on Lake Champlain with mountain views, experience farm-to-table dining, vibrant Church Street, and the Green Mountain State's authentic charm.", highlights: ["Stroll Church Street Marketplace", "Cruise Lake Champlain", "Visit local breweries", "Experience farm-to-table dining", "Explore Burlington waterfront", "Discover local art scene"], startDate: "June 29, 2026", endDate: "July 5, 2026", maxParticipants: 36, imageUrl: "/api/images/vermont.png" },
  { city: "Gray & Boothbay Harbor", state: "Maine", description: "Experience Maine's authentic coastal charm and natural beauty. From Gray's pristine lakes and forests to Boothbay Harbor's working waterfront and fresh lobster, discover Vacationland's timeless appeal.", highlights: ["Visit Boothbay Harbor waterfront", "Enjoy fresh Maine lobster", "Explore coastal villages", "Discover lighthouse tours", "Experience maritime heritage", "Tour local art galleries"], startDate: "July 6, 2026", endDate: "July 12, 2026", maxParticipants: 36, imageUrl: "/api/images/maine.png" },
  { city: "Cincinnati & Newport", state: "Ohio", description: "Explore the Queen City's cultural renaissance and Newport's Kentucky riverfront charm. From Cincinnati's world-class museums and vibrant Over-the-Rhine to Newport's aquarium and historic districts, discover the Ohio River Valley.", highlights: ["Visit Cincinnati Art Museum", "Explore Over-the-Rhine neighborhood", "Tour Newport Aquarium", "Experience Findlay Market", "Discover riverfront parks", "Enjoy Cincinnati chili"], startDate: "July 13, 2026", endDate: "July 19, 2026", maxParticipants: 36, imageUrl: "/api/images/ohio.png" },
  { city: "Detroit", state: "Michigan", description: "Witness Detroit's remarkable comeback story. From Motown heritage and world-class museums to revitalized neighborhoods and innovative food scene, experience the Motor City's creative energy and resilient spirit.", highlights: ["Tour Motown Museum", "Visit Detroit Institute of Arts", "Explore Eastern Market", "Experience Belle Isle Park", "Discover street art in Midtown", "Tour automotive history"], startDate: "July 20, 2026", endDate: "July 26, 2026", maxParticipants: 36, imageUrl: "/api/images/michigan.png" },
  { city: "Indianapolis", state: "Indiana", description: "Discover Indianapolis's sporting heritage and Midwestern charm. From the iconic Motor Speedway and vibrant Mass Ave to world-class museums and canal walks, experience the Crossroads of America.", highlights: ["Tour Indianapolis Motor Speedway", "Walk the Canal downtown", "Visit Indianapolis Museum of Art", "Explore Mass Ave arts district", "Experience Monument Circle", "Discover local breweries"], startDate: "July 27, 2026", endDate: "August 2, 2026", maxParticipants: 36, imageUrl: "/api/images/indiana.png" },
  { city: "Chicago", state: "Illinois", description: "Immerse yourself in Chicago's world-class architecture, deep-dish pizza, and lakefront beauty. From Millennium Park and Navy Pier to diverse neighborhoods and stunning skyline, experience the Windy City's bold energy.", highlights: ["See Cloud Gate at Millennium Park", "Visit Art Institute of Chicago", "Explore Navy Pier", "Take architectural boat tour", "Experience deep-dish pizza", "Discover neighborhood culture"], startDate: "August 3, 2026", endDate: "August 9, 2026", maxParticipants: 36, imageUrl: "/api/images/illinois.png" },
  { city: "Milwaukee", state: "Wisconsin", description: "Experience Milwaukee's brewing heritage and lakefront charm. From historic breweries and vibrant festivals to beautiful Lake Michigan shores and diverse neighborhoods, discover Brew City's authentic culture.", highlights: ["Tour historic breweries", "Visit Milwaukee Art Museum", "Explore Third Ward district", "Experience lakefront festivals", "Discover local cheese culture", "Tour Harley-Davidson Museum"], startDate: "August 10, 2026", endDate: "August 16, 2026", maxParticipants: 36, imageUrl: "/api/images/wisconsin.png" },
  { city: "Apple Valley & Bloomington", state: "Minnesota", description: "Discover the Twin Cities metro's vibrant communities. From Apple Valley's natural preserves and trails to Bloomington's Mall of America and cultural attractions, experience Minnesota nice and urban energy.", highlights: ["Visit Mall of America", "Explore Minnesota Zoo", "Discover local parks and trails", "Experience Minnesota Valley refuge", "Tour local breweries", "Enjoy diverse dining"], startDate: "August 17, 2026", endDate: "August 23, 2026", maxParticipants: 36, imageUrl: "/api/images/minnesota.png" },
  { city: "Fargo & Bismarck", state: "North Dakota", description: "Experience North Dakota's prairie charm and frontier heritage. From Fargo's thriving arts scene and Scandinavian roots to Bismarck's capitol grounds and Missouri River, discover the Peace Garden State.", highlights: ["Visit North Dakota State Capitol", "Explore Fargo-Moorhead arts scene", "Discover frontier history", "Experience prairie landscapes", "Tour heritage centers", "Enjoy local cuisine"], startDate: "August 24, 2026", endDate: "August 30, 2026", maxParticipants: 36, imageUrl: "/api/images/northdakota.png" },
  { city: "Sioux Falls", state: "South Dakota", description: "Discover Sioux Falls' natural beauty and vibrant downtown. From the stunning Falls Park and Big Sioux River to the revitalized 8th & Railroad district, experience South Dakota's largest city and gateway to the West.", highlights: ["Visit Falls Park cascades", "Explore downtown sculpture walk", "Discover 8th & Railroad district", "Tour historic Old Courthouse", "Experience local breweries", "Enjoy Big Sioux River trails"], startDate: "August 31, 2026", endDate: "September 6, 2026", maxParticipants: 36, imageUrl: "/api/images/southdakota.png" },
  { city: "Omaha", state: "Nebraska", description: "Experience Omaha's friendly Midwestern culture and surprising sophistication. From world-class Henry Doorly Zoo and revitalized Old Market to the Bob Kerrey Pedestrian Bridge, discover the Gateway to the West.", highlights: ["Visit Henry Doorly Zoo", "Explore Old Market district", "Walk Bob Kerrey Bridge", "Tour Durham Museum", "Experience local steakhouses", "Discover riverfront trails"], startDate: "September 7, 2026", endDate: "September 13, 2026", maxParticipants: 36, imageUrl: "/api/images/nebraska.png" },
  { city: "Wichita & Kansas City", state: "Kansas", description: "Journey through Kansas' vibrant cities. From Wichita's aviation heritage and arts scene to Kansas City's BBQ culture and revitalized downtown, experience the Sunflower State's urban energy.", highlights: ["Visit Kansas Aviation Museum", "Explore Old Cowtown Museum", "Discover Kansas City BBQ", "Tour Exploration Place", "Experience local arts districts", "Enjoy prairie landscapes"], startDate: "September 14, 2026", endDate: "September 20, 2026", maxParticipants: 36, imageUrl: "/api/images/kansas.png" },
  { city: "St. Louis & Springfield", state: "Missouri", description: "Discover Missouri's Gateway to the West and Route 66 heritage. From St. Louis' iconic Arch and vibrant neighborhoods to Springfield's historic charm, experience Show-Me State culture and history.", highlights: ["Visit Gateway Arch", "Explore Forest Park", "Tour City Museum", "Discover Route 66 heritage", "Experience local BBQ", "Visit historic sites"], startDate: "September 21, 2026", endDate: "September 27, 2026", maxParticipants: 36, imageUrl: "/api/images/missouri.png" },
  { city: "Des Moines & Dubuque", state: "Iowa", description: "Experience Iowa's welcoming cities and scenic river valleys. From Des Moines' capitol grounds and vibrant East Village to Dubuque's historic river port and dramatic bluffs, discover Hawkeye State charm.", highlights: ["Visit Iowa State Capitol", "Explore Des Moines Art Center", "Tour National Mississippi River Museum", "Discover Dubuque bluff views", "Experience local farmers markets", "Visit historic districts"], startDate: "September 28, 2026", endDate: "October 4, 2026", maxParticipants: 36, imageUrl: "/api/images/iowa.png" },
  { city: "Little Rock & Hot Springs", state: "Arkansas", description: "Discover Arkansas' capital city and spa town charm. From Little Rock's civil rights history and River Market to Hot Springs' historic bathhouses and mountain scenery, experience the Natural State.", highlights: ["Visit Little Rock Central High School", "Explore River Market District", "Tour historic bathhouses", "Discover Hot Springs National Park", "Experience local cuisine", "Visit Clinton Presidential Library"], startDate: "October 5, 2026", endDate: "October 11, 2026", maxParticipants: 36, imageUrl: "/api/images/arkansas.png" },
  { city: "New Orleans", state: "Louisiana", description: "Immerse yourself in New Orleans' vibrant culture, jazz heritage, and Creole cuisine. From the French Quarter and live music on Frenchmen Street to historic streetcars and Mississippi River, experience the Big Easy's magic.", highlights: ["Explore French Quarter", "Experience live jazz on Frenchmen Street", "Tour Garden District", "Ride historic streetcars", "Savor Creole and Cajun cuisine", "Visit Jackson Square"], startDate: "October 12, 2026", endDate: "October 18, 2026", maxParticipants: 36, imageUrl: "/api/images/louisiana.png" },
  { city: "Jackson", state: "Mississippi", description: "Discover Mississippi's capital and its rich cultural heritage. From civil rights landmarks and blues history to vibrant arts scene and Southern hospitality, experience the Magnolia State's heart.", highlights: ["Visit Mississippi Civil Rights Museum", "Explore Mississippi Museum of Art", "Tour State Capitol", "Discover local blues heritage", "Experience Southern cuisine", "Visit historic neighborhoods"], startDate: "October 19, 2026", endDate: "October 25, 2026", maxParticipants: 36, imageUrl: "/api/images/mississippi.png" },
  { city: "Birmingham", state: "Alabama", description: "Experience Birmingham's transformation and civil rights legacy. From pivotal historical sites and Vulcan Park to a thriving food scene and revitalized downtown, discover the Magic City's resilience.", highlights: ["Visit Birmingham Civil Rights Institute", "Explore Vulcan Park", "Tour Sloss Furnaces", "Discover Railroad Park", "Experience local BBQ", "Visit historic Kelly Ingram Park"], startDate: "October 26, 2026", endDate: "November 1, 2026", maxParticipants: 36, imageUrl: "/api/images/alabama.png" },
  { city: "Memphis", state: "Tennessee", description: "Immerse yourself in Memphis' soul, blues, and BBQ culture. From Beale Street and Graceland to Sun Studio and Mississippi River views, experience the birthplace of rock 'n' roll.", highlights: ["Visit Graceland", "Experience Beale Street blues", "Tour Sun Studio", "Explore National Civil Rights Museum", "Savor Memphis BBQ", "Walk Mississippi Riverfront"], startDate: "November 2, 2026", endDate: "November 8, 2026", maxParticipants: 36, imageUrl: "/api/images/tennessee.png" },
  { city: "Lexington & Louisville", state: "Kentucky", description: "Experience Kentucky's bourbon heritage and horse country charm. From Lexington's thoroughbred farms to Louisville's Churchill Downs and Bourbon Trail, discover the Bluegrass State's traditions.", highlights: ["Visit Churchill Downs", "Tour bourbon distilleries", "Explore horse farms", "Experience Louisville Slugger Museum", "Discover bourbon heritage", "Visit Kentucky Horse Park"], startDate: "November 9, 2026", endDate: "November 15, 2026", maxParticipants: 36, imageUrl: "/api/images/kentucky.png" },
  { city: "Charleston", state: "South Carolina", description: "Discover Charleston's timeless charm and Southern hospitality. From cobblestone streets and historic Rainbow Row to waterfront parks and world-class cuisine, experience the Holy City's rich heritage and coastal beauty.", highlights: ["Explore historic Rainbow Row", "Tour historic plantations", "Walk the Battery promenade", "Visit Fort Sumter", "Experience Lowcountry cuisine", "Discover historic churches"], startDate: "November 16, 2026", endDate: "November 22, 2026", maxParticipants: 36, imageUrl: "/api/images/southcarolina.png" },
  { city: "Richmond", state: "Virginia", description: "Experience Richmond's layered history and modern renaissance. From Civil War sites and historic Canal Walk to vibrant arts scene and James River adventures, discover Virginia's capital charm.", highlights: ["Visit Virginia State Capitol", "Explore Canal Walk", "Tour American Civil War Museum", "Discover Carytown shopping district", "Experience James River", "Visit historic neighborhoods"], startDate: "November 23, 2026", endDate: "November 29, 2026", maxParticipants: 36, imageUrl: "/api/images/virginia.png" },
  { city: "Raleigh & Durham", state: "North Carolina", description: "Discover North Carolina's Research Triangle innovation and Southern charm. From Raleigh's museums and Durham's vibrant downtown to university culture and local food scene, experience Tar Heel State energy.", highlights: ["Visit North Carolina Museum of Art", "Explore Durham Bulls ballpark", "Tour Duke University", "Discover local breweries", "Experience Southern cuisine", "Visit historic downtown areas"], startDate: "November 30, 2026", endDate: "December 6, 2026", maxParticipants: 36, imageUrl: "/api/images/northcarolina.png" },
  { city: "Columbia & Charleston", state: "South Carolina", description: "Journey through South Carolina from capital to coast. Experience Columbia's State House and riverfront, then Charleston's historic charm, Rainbow Row, and Lowcountry culture.", highlights: ["Tour SC State House", "Explore Charleston historic district", "Visit Rainbow Row", "Discover Lowcountry cuisine", "Experience waterfront parks", "Tour plantations and gardens"], startDate: "December 7, 2026", endDate: "December 13, 2026", maxParticipants: 36, imageUrl: "/api/images/southcarolina.png" },
  { city: "Atlanta & Savannah", state: "Georgia", description: "Experience Georgia's dynamic capital and coastal gem. From Atlanta's skyline and civil rights heritage to Savannah's moss-draped squares and Southern charm, discover Peach State diversity.", highlights: ["Visit Georgia Aquarium", "Explore Savannah historic squares", "Tour MLK Jr. National Historic Site", "Discover River Street", "Experience Southern cuisine", "Visit Forsyth Park"], startDate: "December 14, 2026", endDate: "December 20, 2026", maxParticipants: 36, imageUrl: "/api/images/georgia.png" },
  { city: "Jacksonville", state: "Florida", description: "Discover Jacksonville's beaches, rivers, and vibrant culture. From historic riverside neighborhoods and pristine Atlantic beaches to arts districts and outdoor adventures, experience the Sunshine State's largest city.", highlights: ["Visit Jacksonville Beach", "Explore Riverside and Avondale", "Tour Cummer Museum", "Discover St. Johns River", "Experience local food scene", "Visit historic districts"], startDate: "December 21, 2026", endDate: "December 27, 2026", maxParticipants: 36, imageUrl: "/api/images/florida.png" },
  { city: "Oklahoma City", state: "Oklahoma", description: "Experience Oklahoma City's Western heritage and modern energy. From the moving National Memorial and Bricktown entertainment to Stockyards City and cowboy culture, discover the Sooner State's capital.", highlights: ["Visit Oklahoma City National Memorial", "Explore Bricktown district", "Tour National Cowboy Museum", "Discover Stockyards City", "Experience local cuisine", "Visit Myriad Gardens"], startDate: "December 28, 2026", endDate: "January 3, 2027", maxParticipants: 36, imageUrl: "/api/images/oklahoma.png" },
  { city: "Houston", state: "Texas", description: "Immerse yourself in Houston's space heritage and diverse culture. From NASA Space Center and Museum District to vibrant neighborhoods and world-class dining, experience the largest city in Texas.", highlights: ["Visit Space Center Houston", "Explore Museum District", "Discover diverse neighborhoods", "Experience international cuisine", "Tour downtown theater district", "Visit Buffalo Bayou Park"], startDate: "January 4, 2027", endDate: "January 10, 2027", maxParticipants: 36, imageUrl: "/api/images/texas.png" },
  { city: "Phoenix", state: "Arizona", description: "Discover Phoenix's desert beauty and Southwestern culture. From stunning mountain preserves and vibrant arts scene to Native American heritage and innovative cuisine, experience the Valley of the Sun.", highlights: ["Hike Camelback Mountain", "Visit Desert Botanical Garden", "Explore Heard Museum", "Discover Old Town Scottsdale", "Experience Southwestern cuisine", "Tour Taliesin West"], startDate: "January 11, 2027", endDate: "January 17, 2027", maxParticipants: 36, imageUrl: "/api/images/arizona.png" },
  { city: "Santa Fe & Albuquerque", state: "New Mexico", description: "Experience New Mexico's unique blend of cultures. From Santa Fe's art galleries and adobe architecture to Albuquerque's Old Town and Sandia Mountains, discover Land of Enchantment beauty.", highlights: ["Explore Santa Fe Plaza", "Visit Georgia O'Keeffe Museum", "Tour Albuquerque Old Town", "Discover Native American heritage", "Experience New Mexican cuisine", "Visit art galleries and markets"], startDate: "January 18, 2027", endDate: "January 24, 2027", maxParticipants: 36, imageUrl: "/api/images/newmexico2.png" },
  { city: "Salt Lake City", state: "Utah", description: "Discover Salt Lake City's mountain backdrop and cultural heritage. From Temple Square and vibrant downtown to nearby ski resorts and stunning landscapes, experience Utah's capital beauty.", highlights: ["Visit Temple Square", "Explore Natural History Museum", "Discover Antelope Island", "Experience local food scene", "Tour State Capitol", "Visit nearby canyons"], startDate: "January 25, 2027", endDate: "January 31, 2027", maxParticipants: 36, imageUrl: "/api/images/utah.png" },
  { city: "Las Vegas", state: "Nevada", description: "Experience Las Vegas beyond the Strip. From world-class entertainment and diverse dining to nearby Red Rock Canyon and vibrant arts district, discover the Entertainment Capital's many faces.", highlights: ["Explore Las Vegas Strip", "Visit Arts District", "Discover Red Rock Canyon", "Experience world-class shows", "Tour Fremont Street", "Enjoy diverse dining"], startDate: "February 1, 2027", endDate: "February 7, 2027", maxParticipants: 36, imageUrl: "/api/images/nevada2.png" },
  { city: "Seattle", state: "Washington", description: "Immerse yourself in Seattle's coffee culture, tech innovation, and natural beauty. From Pike Place Market and Space Needle to waterfront views and vibrant neighborhoods, experience the Emerald City.", highlights: ["Visit Pike Place Market", "Explore Space Needle", "Discover Chihuly Garden", "Tour waterfront and ferry", "Experience coffee culture", "Visit diverse neighborhoods"], startDate: "February 8, 2027", endDate: "February 14, 2027", maxParticipants: 36, imageUrl: "/api/images/washington.png" },
  { city: "Anchorage", state: "Alaska", description: "Experience Alaska's largest city surrounded by wilderness. From stunning mountain and inlet views to wildlife encounters and Native Alaskan culture, discover the Last Frontier's gateway.", highlights: ["Visit Alaska Native Heritage Center", "Explore Tony Knowles Coastal Trail", "Discover Anchorage Museum", "Experience wildlife viewing", "Tour local breweries", "Visit nearby glaciers"], startDate: "February 15, 2027", endDate: "February 21, 2027", maxParticipants: 36, imageUrl: "/api/images/alaska.png" },
  { city: "Honolulu", state: "Hawaii", description: "Discover Honolulu's paradise blend of beach culture, Hawaiian heritage, and urban energy. From Waikiki Beach and Diamond Head to historic sites and aloha spirit, experience the Aloha State's capital.", highlights: ["Visit Waikiki Beach", "Hike Diamond Head", "Explore Pearl Harbor", "Discover Iolani Palace", "Experience luau culture", "Enjoy Hawaiian cuisine"], startDate: "February 22, 2027", endDate: "February 28, 2027", maxParticipants: 36, imageUrl: "/api/images/hawaii.png" },
  { city: "Portland & Newport", state: "Oregon", description: "Experience Oregon's creative spirit and coastal beauty. From Portland's food carts, craft breweries, and quirky culture to Newport's dramatic coastline and marine life, discover the Pacific Northwest.", highlights: ["Explore Portland food cart scene", "Visit Powell's City of Books", "Discover Oregon Coast Aquarium", "Experience craft breweries", "Tour Newport waterfront", "Visit Japanese Garden"], startDate: "March 1, 2027", endDate: "March 7, 2027", maxParticipants: 36, imageUrl: "/api/images/oregon.png" },
  { city: "San Diego & Monterey", state: "California", description: "Journey through California's stunning coastline. From San Diego's beaches, Balboa Park, and Gaslamp Quarter to Monterey's Cannery Row and aquarium, experience Golden State coastal charm.", highlights: ["Visit Balboa Park museums", "Explore Gaslamp Quarter", "Tour Monterey Bay Aquarium", "Discover 17-Mile Drive", "Experience beach culture", "Visit historic Cannery Row"], startDate: "March 8, 2027", endDate: "March 14, 2027", maxParticipants: 36, imageUrl: "/api/images/california.png" },
  { city: "Wheeling", state: "West Virginia", description: "Explore Wheeling's rich Victorian heritage and Ohio River charm. From the historic Wheeling Suspension Bridge and Capitol Theatre to vibrant downtown and nearby mountain trails, discover Mountain State hospitality in this historic river city.", highlights: ["Tour Wheeling Suspension Bridge", "Visit Capitol Theatre", "Explore Victorian downtown", "Discover Oglebay Park", "Experience Ohio River heritage", "Tour historic mansions"], startDate: "April 19, 2027", endDate: "April 23, 2027", maxParticipants: 36, imageUrl: "/api/images/westvirginia.png" },
];

async function seedTours() {
  try {
    console.log('Starting CityTourHub tours seeding...');
    
    // Create tables first
    await pool.query(`
      CREATE TABLE IF NOT EXISTS cth_tours (
        id          VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
        city        TEXT NOT NULL,
        state       TEXT NOT NULL,
        description TEXT NOT NULL,
        highlights  TEXT[] NOT NULL DEFAULT '{}',
        start_date  TEXT NOT NULL,
        end_date    TEXT NOT NULL,
        max_participants     INTEGER NOT NULL,
        current_participants INTEGER NOT NULL DEFAULT 0,
        image_url   TEXT NOT NULL,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    console.log('✓ Table cth_tours ensured');
    
    // Check if tours already exist
    const { rows: existing } = await pool.query('SELECT COUNT(*) FROM cth_tours');
    const count = Number(existing[0].count);
    
    if (count > 0) {
      console.log(`✓ ${count} tours already exist in database. Skipping seed.`);
      await pool.end();
      process.exit(0);
    }
    
    // Insert all tours
    let inserted = 0;
    for (const tour of tourData) {
      await pool.query(
        `INSERT INTO cth_tours (city, state, description, highlights, start_date, end_date, max_participants, current_participants, image_url)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
        [
          tour.city,
          tour.state,
          tour.description,
          tour.highlights,
          tour.startDate,
          tour.endDate,
          tour.maxParticipants,
          0,
          tour.imageUrl,
        ]
      );
      inserted++;
    }
    
    console.log(`✓ Successfully seeded ${inserted} tours into cth_tours`);
    
    // Verify
    const { rows: final } = await pool.query('SELECT COUNT(*) as total, COUNT(DISTINCT state) as states FROM cth_tours');
    console.log(`✓ Database now contains ${final[0].total} tours across ${final[0].states} states`);
    
    await pool.end();
    process.exit(0);
  } catch (err) {
    console.error('Seeding failed:', err);
    await pool.end();
    process.exit(1);
  }
}

seedTours();
