const pool = require('../db');

const toursData = [
    {
        city: "Baltimore",
        state: "Maryland",
        description: "Discover a harbor city bursting with creativity, culture, and waterfront energy — from the iconic Inner Harbor, vibrant Fells Point and Federal Hill neighborhoods, and rich maritime history, to local art at the Baltimore Museum of Art and flavors of Maryland blue crab.",
        highlights: ["Explore the historic Inner Harbor", "Visit Fells Point neighborhood", "Tour Baltimore Museum of Art", "Experience Federal Hill views", "Taste Maryland blue crab", "Discover maritime history"],
        startDate: "April 27, 2026",
        endDate: "May 3, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Baltimore_Inner_Harbor_sunset_9e4ce905.png",
    },
    {
        city: "Wilmington & Rehoboth Beach",
        state: "Delaware",
        description: "Experience Delaware's perfect blend of historic charm and coastal beauty. From Wilmington's vibrant downtown and DuPont heritage sites to the pristine beaches and boardwalk of Rehoboth Beach, discover the First State's diverse treasures.",
        highlights: ["Tour DuPont mansions and gardens", "Explore Wilmington Riverfront", "Relax on Rehoboth Beach boardwalk", "Visit Delaware Art Museum", "Enjoy fresh seafood dining", "Discover tax-free shopping"],
        startDate: "May 4, 2026",
        endDate: "May 10, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Rehoboth_Beach_Delaware_coast_ac3a446d.png",
    },
    {
        city: "Philadelphia & Pittsburgh",
        state: "Pennsylvania",
        description: "Journey through Pennsylvania's iconic cities - from Philadelphia's birthplace of American democracy and vibrant arts scene to Pittsburgh's transformed waterfront and innovative spirit. Experience the Keystone State's rich history and modern energy.",
        highlights: ["See the Liberty Bell and Independence Hall", "Explore Philadelphia Museum of Art", "Visit Pittsburgh's Strip District", "Tour Andy Warhol Museum", "Experience cheesesteak culture", "Discover Steel City transformation"],
        startDate: "May 11, 2026",
        endDate: "May 17, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Philadelphia_Pennsylvania_Independence_Hall_21cd5305.png",
    },
    {
        city: "West Orange & Camden",
        state: "New Jersey",
        description: "Uncover New Jersey's innovation heritage and waterfront renaissance. From Thomas Edison's laboratory in West Orange to Camden's revitalized waterfront with spectacular Philadelphia skyline views, experience the Garden State's hidden gems.",
        highlights: ["Tour Edison National Historic Site", "Visit Adventure Aquarium in Camden", "Explore Battleship New Jersey", "Discover South Mountain Reservation", "Experience waterfront entertainment", "Enjoy diverse culinary scene"],
        startDate: "May 18, 2026",
        endDate: "May 24, 2026",
        maxParticipants: 36,
        imageUrl: "/images/West_Orange_New_Jersey_0cfb8157.png",
    },
    {
        city: "Bronx & Brooklyn",
        state: "New York",
        description: "Immerse yourself in New York City's diverse boroughs. From the Bronx Zoo and Yankee Stadium to Brooklyn's vibrant neighborhoods, world-class museums, and iconic Brooklyn Bridge, discover the authentic heart of the Big Apple.",
        highlights: ["Visit Bronx Zoo and Botanical Garden", "Tour Yankee Stadium", "Walk Brooklyn Bridge", "Explore DUMBO and Williamsburg", "Experience Brooklyn Museum", "Enjoy diverse food scenes"],
        startDate: "May 25, 2026",
        endDate: "May 31, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Brooklyn_New_York_skyline_view_c67254f4.png",
    },
    {
        city: "Bridgeport & Mystic",
        state: "Connecticut",
        description: "Explore Connecticut's coastal treasures from Bridgeport's Barnum legacy and Sound views to Mystic's maritime heritage and charming seaport. Experience New England coastal culture at its finest.",
        highlights: ["Visit Mystic Seaport Museum", "Explore Beardsley Zoo", "Tour historic whaling village", "Experience maritime heritage", "Enjoy coastal seafood", "Discover local art galleries"],
        startDate: "June 1, 2026",
        endDate: "June 7, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Mystic_Connecticut_seaport_charm_0337b7e2.png",
    },
    {
        city: "Providence & North Kingstown",
        state: "Rhode Island",
        description: "Discover Rhode Island's creative spirit and coastal charm. From Providence's renaissance as a cultural hub with world-class design schools to North Kingstown's pristine beaches and historic villages, experience the Ocean State's unique character.",
        highlights: ["Tour RISD Museum", "Explore WaterFire Providence", "Visit historic Wickford Village", "Discover Benefit Street architecture", "Enjoy fresh seafood", "Experience coastal beaches"],
        startDate: "June 8, 2026",
        endDate: "June 14, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Providence_Rhode_Island_historic_49afbec9.png",
    },
    {
        city: "Boston",
        state: "Massachusetts",
        description: "Walk through America's revolutionary history and modern innovation in Boston. From the Freedom Trail and Fenway Park to world-class museums and vibrant neighborhoods, experience the city where American independence was born.",
        highlights: ["Walk the Freedom Trail", "Visit Faneuil Hall Marketplace", "Tour Fenway Park", "Explore Museum of Fine Arts", "Experience North End Italian cuisine", "Discover Boston Harbor"],
        startDate: "June 15, 2026",
        endDate: "June 21, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Boston_Massachusetts_historic_harbor_02bc8640.png",
    },
    {
        city: "Holderness & Hampton Beach",
        state: "New Hampshire",
        description: "Experience New Hampshire's natural beauty and coastal fun. From the pristine lakes and White Mountains near Holderness to the lively Hampton Beach boardwalk, discover the Granite State's outdoor paradise.",
        highlights: ["Explore Squam Lake", "Visit Hampton Beach boardwalk", "Discover White Mountains views", "Experience lakeside activities", "Enjoy fresh seafood", "Tour scenic drives"],
        startDate: "June 22, 2026",
        endDate: "June 28, 2026",
        maxParticipants: 36,
        imageUrl: "/images/New_Hampshire_lake_scenery_15a49902.png",
    },
    {
        city: "Burlington",
        state: "Vermont",
        description: "Discover Burlington's perfect blend of natural beauty and creative culture. Nestled on Lake Champlain with mountain views, experience farm-to-table dining, vibrant Church Street, and the Green Mountain State's authentic charm.",
        highlights: ["Stroll Church Street Marketplace", "Cruise Lake Champlain", "Visit local breweries", "Experience farm-to-table dining", "Explore Burlington waterfront", "Discover local art scene"],
        startDate: "June 29, 2026",
        endDate: "July 5, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Burlington_Vermont_lakefront_d53b9a48.png",
    },
    {
        city: "Gray & Boothbay Harbor",
        state: "Maine",
        description: "Experience Maine's authentic coastal charm and natural beauty. From Gray's pristine lakes and forests to Boothbay Harbor's working waterfront and fresh lobster, discover Vacationland's timeless appeal.",
        highlights: ["Visit Boothbay Harbor waterfront", "Enjoy fresh Maine lobster", "Explore coastal villages", "Discover lighthouse tours", "Experience maritime heritage", "Tour local art galleries"],
        startDate: "July 6, 2026",
        endDate: "July 12, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Portland_Maine_Old_Port_600d29a9.png",
    },
    {
        city: "Cincinnati & Newport",
        state: "Ohio",
        description: "Explore the Queen City's cultural renaissance and Newport's Kentucky riverfront charm. From Cincinnati's world-class museums and vibrant Over-the-Rhine to Newport's aquarium and historic districts, discover the Ohio River Valley.",
        highlights: ["Visit Cincinnati Art Museum", "Explore Over-the-Rhine neighborhood", "Tour Newport Aquarium", "Experience Findlay Market", "Discover riverfront parks", "Enjoy Cincinnati chili"],
        startDate: "July 13, 2026",
        endDate: "July 19, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Cincinnati_Ohio_riverfront_bridge_de856b91.png",
    },
    {
        city: "Detroit",
        state: "Michigan",
        description: "Witness Detroit's remarkable comeback story. From Motown heritage and world-class museums to revitalized neighborhoods and innovative food scene, experience the Motor City's creative energy and resilient spirit.",
        highlights: ["Tour Motown Museum", "Visit Detroit Institute of Arts", "Explore Eastern Market", "Experience Belle Isle Park", "Discover street art in Midtown", "Tour automotive history"],
        startDate: "July 20, 2026",
        endDate: "July 26, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Detroit_Michigan_Renaissance_Center_37540d93.png",
    },
    {
        city: "Indianapolis",
        state: "Indiana",
        description: "Discover Indianapolis's sporting heritage and Midwestern charm. From the iconic Motor Speedway and vibrant Mass Ave to world-class museums and canal walks, experience the Crossroads of America.",
        highlights: ["Tour Indianapolis Motor Speedway", "Walk the Canal downtown", "Visit Indianapolis Museum of Art", "Explore Mass Ave arts district", "Experience Monument Circle", "Discover local breweries"],
        startDate: "July 27, 2026",
        endDate: "August 2, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Indianapolis_Indiana_downtown_2884bae2.png",
    },
    {
        city: "Chicago",
        state: "Illinois",
        description: "Immerse yourself in Chicago's world-class architecture, deep-dish pizza, and lakefront beauty. From Millennium Park and Navy Pier to diverse neighborhoods and stunning skyline, experience the Windy City's bold energy.",
        highlights: ["See Cloud Gate at Millennium Park", "Visit Art Institute of Chicago", "Explore Navy Pier", "Take architectural boat tour", "Experience deep-dish pizza", "Discover neighborhood culture"],
        startDate: "August 3, 2026",
        endDate: "August 9, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Chicago_Illinois_lakefront_skyline_41301165.png",
    },
    {
        city: "Milwaukee",
        state: "Wisconsin",
        description: "Experience Milwaukee's brewing heritage and lakefront charm. From historic breweries and vibrant festivals to beautiful Lake Michigan shores and diverse neighborhoods, discover Brew City's authentic culture.",
        highlights: ["Tour historic breweries", "Visit Milwaukee Art Museum", "Explore Third Ward district", "Experience lakefront festivals", "Discover local cheese culture", "Tour Harley-Davidson Museum"],
        startDate: "August 10, 2026",
        endDate: "August 16, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Milwaukee_Wisconsin_lakefront_d5f5ee64.png",
    },
    {
        city: "Apple Valley & Bloomington",
        state: "Minnesota",
        description: "Discover the Twin Cities metro's vibrant communities. From Apple Valley's natural preserves and trails to Bloomington's Mall of America and cultural attractions, experience Minnesota nice and urban energy.",
        highlights: ["Visit Mall of America", "Explore Minnesota Zoo", "Discover local parks and trails", "Experience Minnesota Valley refuge", "Tour local breweries", "Enjoy diverse dining"],
        startDate: "August 17, 2026",
        endDate: "August 23, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Minneapolis_Minnesota_skyline_35dd8d67.png",
    },
    {
        city: "Fargo & Bismarck",
        state: "North Dakota",
        description: "Experience North Dakota's prairie charm and frontier heritage. From Fargo's thriving arts scene and Scandinavian roots to Bismarck's capitol grounds and Missouri River, discover the Peace Garden State.",
        highlights: ["Visit North Dakota State Capitol", "Explore Fargo-Moorhead arts scene", "Discover frontier history", "Experience prairie landscapes", "Tour heritage centers", "Enjoy local cuisine"],
        startDate: "August 24, 2026",
        endDate: "August 30, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Fargo_North_Dakota_downtown_1875d69d.png",
    },
    {
        city: "Sioux Falls",
        state: "South Dakota",
        description: "Discover Sioux Falls' natural beauty and vibrant downtown. From the stunning Falls Park and Big Sioux River to the revitalized 8th & Railroad district, experience South Dakota's largest city and gateway to the West.",
        highlights: ["Visit Falls Park cascades", "Explore downtown sculpture walk", "Discover 8th & Railroad district", "Tour historic Old Courthouse", "Experience local breweries", "Enjoy Big Sioux River trails"],
        startDate: "August 31, 2026",
        endDate: "September 6, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Sioux_Falls_South_Dakota_87bd3c26.png",
    },
    {
        city: "Omaha",
        state: "Nebraska",
        description: "Experience Omaha's friendly Midwestern culture and surprising sophistication. From world-class Henry Doorly Zoo and revitalized Old Market to the Bob Kerrey Pedestrian Bridge, discover the Gateway to the West.",
        highlights: ["Visit Henry Doorly Zoo", "Explore Old Market district", "Walk Bob Kerrey Bridge", "Tour Durham Museum", "Experience local steakhouses", "Discover riverfront trails"],
        startDate: "September 7, 2026",
        endDate: "September 13, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Omaha_Nebraska_riverfront_07e25ea8.png",
    },
    {
        city: "Wichita & Kansas City",
        state: "Kansas",
        description: "Experience Kansas's cultural crossroads where prairie meets innovation. From Wichita's aviation heritage and local art scene to Kansas City's cultural attractions and Flint Hills beauty, discover the Sunflower State.",
        highlights: ["Visit Wichita Aviation Museum", "Explore Intrepid Museum", "Discover Wichita cultural attractions", "Experience Flint Hills prairie", "Tour local breweries", "Enjoy Kansas heritage"],
        startDate: "September 14, 2026",
        endDate: "September 20, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Kansas_City_riverfront_skyline_808f8159.png",
    },
    {
        city: "St. Louis & Springfield",
        state: "Missouri",
        description: "Journey through Missouri's iconic landmarks and historic significance. From St. Louis's Gateway Arch and revitalized waterfront to Springfield's Lincoln heritage, discover the Show-Me State's soul.",
        highlights: ["Experience Gateway Arch", "Explore St. Louis City Museum", "Visit City Museum", "Tour Lincoln sites in Springfield", "Discover Riverboat heritage", "Experience BBQ culture"],
        startDate: "September 21, 2026",
        endDate: "September 27, 2026",
        maxParticipants: 36,
        imageUrl: "/images/St_Louis_Missouri_Gateway_Arch_34217ea3.png",
    },
    {
        city: "Des Moines & Dubuque",
        state: "Iowa",
        description: "Explore Iowa's blend of urban energy and Mississippi River charm. From Des Moines's vibrant arts and culture scene to Dubuque's historic riverfront, discover the Hawkeye State's surprising sophistication.",
        highlights: ["Visit Des Moines Art Center", "Explore Dubuque riverfront", "Tour historic Victorian homes", "Discover local farmers markets", "Experience scenic drives", "Enjoy heartland hospitality"],
        startDate: "September 28, 2026",
        endDate: "October 4, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Des_Moines_Iowa_capital_4deb3a10.png",
    },
    {
        city: "Little Rock & Hot Springs",
        state: "Arkansas",
        description: "Uncover Arkansas's natural thermal wonders and presidential history. From Little Rock's cultural renaissance and historic significance to Hot Springs' natural bathhouses and mountain beauty, discover the Natural State.",
        highlights: ["Visit Central High Site", "Tour presidential library", "Bathe in Hot Springs bathhouses", "Explore Hot Springs Mountain Tower", "Discover Caddo River trails", "Experience local Southern cuisine"],
        startDate: "October 5, 2026",
        endDate: "October 11, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Little_Rock_Arkansas_riverfront_c926e1ff.png",
    },
    {
        city: "New Orleans",
        state: "Louisiana",
        description: "Immerse yourself in New Orleans' unmatched cultural richness and vibrant spirit. From the French Quarter's historic charm and jazz heritage to Creole cuisine and Mardi Gras traditions, experience America's most unique city.",
        highlights: ["Explore French Quarter", "Enjoy live jazz venues", "Learn Voodoo history", "Sample Creole cuisine", "Tour historic neighborhoods", "Experience Southern hospitality"],
        startDate: "October 12, 2026",
        endDate: "October 18, 2026",
        maxParticipants: 36,
        imageUrl: "/images/New_Orleans_French_Quarter_f0d4b86d.png",
    },
    {
        city: "Jackson",
        state: "Mississippi",
        description: "Discover Mississippi's civil rights history and cultural heritage. From Jackson's museums and Mississippi River connections to Delta blues and Southern traditions, experience the Deep South's powerful story.",
        highlights: ["Tour Civil Rights Museum", "Visit Mississippi History Museum", "Explore Delta blues heritage", "Discover Louisiana Purchase Monument", "Experience Southern cuisine", "Learn Mississippi heritage"],
        startDate: "October 19, 2026",
        endDate: "October 25, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Jackson_Mississippi_capital_city_857f3f77.png",
    },
    {
        city: "Birmingham",
        state: "Alabama",
        description: "Explore Birmingham's transformation and rich history. From the Civil Rights District and civil rights museums to the thriving foodie scene and revitalized neighborhoods, discover Birmingham's dynamic spirit.",
        highlights: ["Visit Civil Rights District", "Tour 16th Street Baptist Church", "Explore Vulcan Park", "Experience local chef scene", "Discover Sloss Furnaces history", "Tour historic neighborhoods"],
        startDate: "October 26, 2026",
        endDate: "November 1, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Birmingham_Alabama_cityscape_689f776e.png",
    },
    {
        city: "Memphis",
        state: "Tennessee",
        description: "Experience Memphis's legendary music heritage and cultural vitality. From Graceland and Beale Street to soul food and the Mississippi River, discover the Home of the Blues.",
        highlights: ["Visit Graceland", "Explore Beale Street jazz clubs", "Tour Memphis Soul Museum", "Visit National Civil Rights Museum", "Experience BBQ culture", "Cruise Mississippi River"],
        startDate: "November 2, 2026",
        endDate: "November 8, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Nashville_skyline_at_dusk_81989aa1.png",
    },
    {
        city: "Lexington & Louisville",
        state: "Kentucky",
        description: "Discover Kentucky's blend of bourbon heritage, horse country, and Southern grace. From Lexington's horse farms and Louisville's bourbon distilleries to music and culinary scenes, experience the Bluegrass State.",
        highlights: ["Tour bourbon distilleries", "Visit horse farms", "Experience Louisville waterfront", "Discover Kentucky bourbon trail", "Enjoy Southern hospitality", "Tour historic mansions"],
        startDate: "November 9, 2026",
        endDate: "November 15, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Louisville_Kentucky_riverfront_77b9822a.png",
    },
    {
        city: "Charleston",
        state: "South Carolina",
        description: "Explore Charleston's timeless elegance and rich history. From Rainbow Row and historic plantations to lowcountry cuisine and Southern charm, discover one of America's most beautiful cities.",
        highlights: ["Explore Rainbow Row architecture", "Tour historic plantations", "Experience Fort Sumter", "Enjoy lowcountry dining", "Walk historic streets", "Tour local galleries"],
        startDate: "November 16, 2026",
        endDate: "November 22, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Charleston_Rainbow_Row_houses_580fc3c6.png",
    },
    {
        city: "Richmond",
        state: "Virginia",
        description: "Discover Richmond's pivotal role in American history and modern renaissance. From Monument Avenue and Capitol Square to world-class restaurants and James River trails, experience Virginia's dynamic capital.",
        highlights: ["Tour Capitol building", "Explore Monument Avenue", "Visit Civil War museums", "Walk James River trails", "Experience local food scene", "Tour historic neighborhoods"],
        startDate: "November 23, 2026",
        endDate: "November 29, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Richmond_Virginia_capital_a46b7bfa.png",
    },
    {
        city: "Raleigh & Durham",
        state: "North Carolina",
        description: "Experience the Triangle's innovation hub and Piedmont charm. From Research Triangle's tech culture and universities to Raleigh's vibrant downtown and Durham's revitalization, discover North Carolina's dynamic core.",
        highlights: ["Explore Research Triangle attractions", "Visit North Carolina Museum of Art", "Tour downtown neighborhoods", "Experience local food culture", "Discover brewery scene", "Walk nature trails"],
        startDate: "November 30, 2026",
        endDate: "December 6, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Raleigh_North_Carolina_downtown_81039abc.png",
    },
    {
        city: "Columbia & Charleston",
        state: "South Carolina",
        description: "Experience South Carolina's dual charm of culture and coastal beauty. From Columbia's vibrant Congaree riverfront and historic State House to Charleston's timeless elegance, discover the Palmetto State.",
        highlights: ["Explore Columbia riverfront", "Tour State House grounds", "Visit South Carolina Museum", "Enjoy Charleston architecture", "Experience Lowcountry culture", "Walk historic districts"],
        startDate: "December 7, 2026",
        endDate: "December 13, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Savannah_historic_square_oaks_88b92e3f.png",
    },
    {
        city: "Atlanta & Savannah",
        state: "Georgia",
        description: "Discover Georgia's New South energy and historic charm. From Atlanta's dynamic culture and civil rights history to Savannah's Spanish moss-draped squares and coastal beauty, experience Southern sophistication.",
        highlights: ["Tour Georgia Aquarium", "Visit MLK National Historic Site", "Explore Savannah historic squares", "Experience Southern cuisine", "Tour historic neighborhoods", "Enjoy local arts scene"],
        startDate: "December 14, 2026",
        endDate: "December 20, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Savannah_historic_square_oaks_88b92e3f.png",
    },
    {
        city: "Jacksonville",
        state: "Florida",
        description: "Explore Jacksonville's transforming waterfront and authentic Southern charm. From the pristine beaches and historic River Oaks neighborhood to craft breweries and cultural attractions, discover Northeast Florida.",
        highlights: ["Enjoy pristine beaches", "Tour historic neighborhoods", "Visit Cummer Museum", "Experience craft breweries", "Explore riverfront parks", "Discover local food scene"],
        startDate: "December 21, 2026",
        endDate: "December 27, 2026",
        maxParticipants: 36,
        imageUrl: "/images/Jacksonville_Florida_riverfront_skyline_241db261.png",
    },
    {
        city: "Oklahoma City",
        state: "Oklahoma",
        description: "Discover Oklahoma City's resilience and cultural spirit. From the National Memorial and world-class Bricktown to Route 66 heritage and cowboy culture, experience the Sooner State's authentic character.",
        highlights: ["Visit National Memorial", "Explore Bricktown district", "Tour Route 66 sites", "Experience Western heritage", "Discover local museums", "Enjoy Oklahoma cuisine"],
        startDate: "January 11, 2027",
        endDate: "January 17, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Oklahoma_City_skyline_97969b85.png",
    },
    {
        city: "Houston",
        state: "Texas",
        description: "Experience Houston's diverse energy and world-class culture. From the Museum District and Space Center to multicultural neighborhoods and innovative food scene, discover Texas's largest city.",
        highlights: ["Visit NASA Space Center", "Explore Museum District", "Tour diverse neighborhoods", "Experience international cuisine", "Discover craft breweries", "Walk Hermann Park"],
        startDate: "January 18, 2027",
        endDate: "January 24, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Houston_Texas_skyline_7c0112a2.png",
    },
    {
        city: "Denver",
        state: "Colorado",
        description: "Explore Denver's mountain-backed energy and cultural scene. From Rocky Mountain views and craft beer culture to world-class museums and thriving neighborhoods, discover the Mile High City.",
        highlights: ["Enjoy Rocky Mountain views", "Tour craft breweries", "Visit Denver Art Museum", "Explore downtown neighborhoods", "Experience outdoor activities", "Discover local food scene"],
        startDate: "February 1, 2027",
        endDate: "February 7, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Denver_Colorado_mountain_skyline_5704a94b.png",
    },
    {
        city: "Phoenix",
        state: "Arizona",
        description: "Discover Phoenix's vibrant desert energy and outdoor lifestyle. From the Valley of the Sun's modern architecture to Sonoran Desert beauty and local food culture, experience Arizona's largest city.",
        highlights: ["Explore Desert Botanical Garden", "Tour modern architecture", "Visit art museums", "Experience Sonoran Desert", "Enjoy local cuisine", "Discover hiking trails"],
        startDate: "February 8, 2027",
        endDate: "February 14, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Phoenix_Arizona_desert_skyline_b317b961.png",
    },
    {
        city: "Santa Fe & Albuquerque",
        state: "New Mexico",
        description: "Experience New Mexico's artistic spirit and cultural richness. From Santa Fe's adobe architecture and art galleries to Albuquerque's Native American heritage and Balloon Fiesta traditions, discover the Land of Enchantment.",
        highlights: ["Explore Santa Fe Plaza", "Tour art galleries", "Visit Native American sites", "Experience local cuisine", "Discover pueblo culture", "Enjoy mountain scenery"],
        startDate: "February 15, 2027",
        endDate: "February 21, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Santa_Fe_New_Mexico_adobe_3b5c5a76.png",
    },
    {
        city: "Salt Lake City",
        state: "Utah",
        description: "Discover Salt Lake City's blend of urban excitement and Wasatch Mountain beauty. From downtown cultural attractions and Temple Square to world-class skiing and outdoor adventures, experience the Beehive State.",
        highlights: ["Visit Temple Square", "Explore downtown attractions", "Tour Wasatch Mountains", "Experience skiing", "Discover local culture", "Enjoy outdoor activities"],
        startDate: "February 22, 2027",
        endDate: "February 28, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Salt_Lake_City_Utah_mountains_6637f113.png",
    },
    {
        city: "Las Vegas",
        state: "Nevada",
        description: "Experience Las Vegas's legendary entertainment and surprising culture. From the iconic Strip and world-class shows to downtown's creative revival and nearby Red Rock beauty, discover Sin City's multifaceted appeal.",
        highlights: ["Explore the iconic Strip", "Enjoy world-class entertainment", "Visit downtown casinos", "Experience local food scene", "Visit Red Rock Canyon", "Tour vintage Vegas history"],
        startDate: "March 1, 2027",
        endDate: "March 7, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Las_Vegas_Nevada_Strip_44a0c6f4.png",
    },
    {
        city: "Boise",
        state: "Idaho",
        description: "Discover Boise's thriving outdoor culture and vibrant community. From the Foothills and Boise Greenbelt to the downtown food scene and craft breweries, experience Idaho's surprising sophistication.",
        highlights: ["Explore Boise Foothills trails", "Walk the Greenbelt", "Visit art galleries", "Experience local food culture", "Tour craft breweries", "Enjoy outdoor activities"],
        startDate: "March 8, 2027",
        endDate: "March 14, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Boise_Idaho_foothills_view_aa42005c.png",
    },
    {
        city: "Seattle",
        state: "Washington",
        description: "Explore Seattle's innovative spirit and natural beauty. From Pike Place Market and Space Needle to coffee culture, tech scene, and Puget Sound views, discover the Emerald City.",
        highlights: ["Visit Pike Place Market", "See Space Needle", "Explore Capitol Hill", "Tour Boeing Factory", "Enjoy coffee culture", "Discover waterfront parks"],
        startDate: "March 15, 2027",
        endDate: "March 21, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Seattle_Washington_Space_Needle_f348659d.png",
    },
    {
        city: "Portland",
        state: "Oregon",
        description: "Experience Portland's creative energy and natural splendor. From the Forest Park and Willamette River to quirky neighborhoods, coffee culture, and craft beer scene, discover the City of Roses.",
        highlights: ["Explore Forest Park trails", "Visit Portland Art Museum", "Tour quirky neighborhoods", "Enjoy coffee culture", "Experience craft breweries", "Walk along Willamette River"],
        startDate: "March 22, 2027",
        endDate: "March 28, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Portland_Oregon_mountain_backdrop_7f916ea8.png",
    },
    {
        city: "San Diego",
        state: "California",
        description: "Discover San Diego's year-round sunshine and diverse attractions. From Balboa Park and pristine beaches to vibrant neighborhoods and fresh Pacific seafood, experience Southern California's best.",
        highlights: ["Explore Balboa Park museums", "Visit pristine beaches", "Tour historic Old Town", "Experience craft beer scene", "Enjoy waterfront dining", "Discover local culture"],
        startDate: "March 29, 2027",
        endDate: "April 4, 2027",
        maxParticipants: 36,
        imageUrl: "/images/San_Diego_California_harbor_view_4380b182.png",
    },
    {
        city: "Bozeman",
        state: "Montana",
        description: "Experience Bozeman's mountain town charm and outdoor culture. From the Bridger Mountains and pristine outdoor recreation to the vibrant downtown and local food scene, discover Montana's gateway.",
        highlights: ["Explore Bridger Mountains", "Visit Montana Museum of the Rockies", "Tour downtown Bozeman", "Experience outdoor recreation", "Discover local breweries", "Enjoy Rocky Mountain views"],
        startDate: "April 5, 2027",
        endDate: "April 11, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Bozeman_Montana_mountain_town_d16d5f94.png",
    },
    {
        city: "Jackson Hole",
        state: "Wyoming",
        description: "Uncover Jackson Hole's legendary outdoor adventures and mountain majesty. From the stunning Teton Range and world-class skiing to town square charm and wildlife encounters, discover the ski capital of North America.",
        highlights: ["Experience Teton Range views", "Tour art galleries", "Visit Jackson town square", "Experience wildlife encounters", "Explore outdoor activities", "Discover Mountain West culture"],
        startDate: "April 12, 2027",
        endDate: "April 18, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Jackson_Hole_Wyoming_Tetons_e0329978.png",
    },
    {
        city: "Anchorage",
        state: "Alaska",
        description: "Experience Alaska's wild beauty and frontier spirit. From the Chugach Mountains and wildlife viewing to the Tony Knowles Trail and local food culture, discover America's Last Frontier.",
        highlights: ["View Chugach Mountains", "Spot wildlife", "Walk Tony Knowles Trail", "Visit Native heritage centers", "Experience outdoor activities", "Discover Alaska culture"],
        startDate: "April 19, 2027",
        endDate: "April 25, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Anchorage_Alaska_mountain_backdrop_441ca7f7.png",
    },
    {
        city: "Honolulu",
        state: "Hawaii",
        description: "Immerse yourself in Honolulu's tropical paradise and multicultural spirit. From pristine beaches and Waikiki charm to historical Pearl Harbor and aloha culture, discover the island capital.",
        highlights: ["Relax on Waikiki Beach", "Visit Pearl Harbor", "Explore Diamond Head", "Tour Honolulu museums", "Experience local cuisine", "Discover Hawaiian culture"],
        startDate: "April 26, 2027",
        endDate: "May 2, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Honolulu_Hawaii_Waikiki_Beach_616f79ac.png",
    },
    {
        city: "Wheeling",
        state: "West Virginia",
        description: "Discover Wheeling's architectural grandeur and Ohio River charm. From the iconic Suspension Bridge and Victorian neighborhoods to the Oglebay Park and riverfront renaissance, experience the Wheeling Renaissance.",
        highlights: ["See iconic Suspension Bridge", "Tour Victorian homes", "Explore Oglebay Park", "Visit riverfront attractions", "Discover local history", "Experience Ohio River views"],
        startDate: "May 3, 2027",
        endDate: "May 9, 2027",
        maxParticipants: 36,
        imageUrl: "/images/Wheeling_Suspension_Bridge_view_c2beaa3e.png",
    },
];

async function seedTours() {
    try {
        console.log('Starting tour seed...');

        // Insert all tours
        for (const tour of toursData) {
            try {
                const query = `
          INSERT INTO cth_tours 
          (city, state, description, highlights, start_date, end_date, max_participants, current_participants, image_url)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
          RETURNING id;
        `;

                const values = [
                    tour.city,
                    tour.state,
                    tour.description,
                    tour.highlights,
                    tour.startDate,
                    tour.endDate,
                    tour.maxParticipants,
                    0,
                    tour.imageUrl
                ];

                const result = await pool.query(query, values);
                console.log(`✓ Seeded: ${tour.city}, ${tour.state} (ID: ${result.rows[0].id}) with image: ${tour.imageUrl}`);
            } catch (err) {
                console.error(`✗ Error seeding ${tour.city}: ${err.message}`);
            }
        }

        // Verify seed
        const countResult = await pool.query('SELECT COUNT(*) FROM cth_tours');
        const count = countResult.rows[0].count;
        console.log(`\n✓ Seeding complete! Total tours in database: ${count}`);

        await pool.end();
    } catch (error) {
        console.error('Seeding failed:', error);
        process.exit(1);
    }
}

seedTours();
